name: SoCal.. SoFar
favicon: null
layout_spectrum: 0.24665
typography_spectrum: 0.25081
title: SoCal.. SoFar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b516e'
    - '#000000'
    - '#dadbdd'
    - '#403329'
    - '#816a50'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.29524061898700893
purpose: []
