name: SoCal.. SoFar
favicon: null
layout_spectrum: 0.4379
typography_spectrum: 0.25168
title: SoCal.. SoFar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71876927-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b516e'
    - '#000000'
    - '#dadbdd'
    - '#403329'
    - '#816a50'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
