name: SoCal.. SoFar
favicon: null
layout_spectrum: 0.6478106072172523
typography_spectrum: 0.3959
title: SoCal.. SoFar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71876927-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2ee'
    - '#faf8f2'
    - '#fdfcf9'
    - '#efece9'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
