name: SoCal.. SoFar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46744
title: SoCal.. SoFar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b516e'
    - '#000000'
    - '#dadbdd'
    - '#403329'
    - '#816a50'
  brandStrength: 0.5
  lightness: 0.7378743225708604
  saturation: 0.1575335138477385
  rhythmicContrast: 0.29524061898700893
purpose: []
